### ISSUE TITLE
App functional

### ISSUE THREAD

**Issue by kolanski** [lbdroid/HFPClient#2]
Hi, is this app turn my phone to handsfree device? like i have ability to connect my phone, to another, and listen music and smth. Any android version prefrences? And how to test it:) On my all devices ag option, in available services ,disable.Thx

**Comment by lbdroid** [comment]
It will only work on devices that have their OS built as supporting HFP client. Your phone is most certainly *not*, unless it is a nexus 5 and you have built your own OS using the HFP test client device tree.

This package is more useful to install onto a car radio.

**Comment by kolanski** [comment]
Many thanx, i stucked with this! Gone for nexus 5. So another question, can you provide links or smth for looking more about bluetooth profile? i dont fully understand how to test whats device correctly routes audio from smartphone to my hfpclient device. And can you get me link for yours nexus 5 firmware?

**Comment by lbdroid** [comment]
https://android.googlesource.com/device/lge/hammerhead/

You're on your own with this.
Like I've said, I'm working on car radios, not phones.

**Comment by lbdroid** [comment]
FYI: This is the product you're looking for;
https://android.googlesource.com/device/lge/hammerhead/+/android-6.0.1_r81/car_hammerhead.mk

Which essentially just turns this file on;
https://android.googlesource.com/device/lge/hammerhead/+/android-6.0.1_r81/overlay_car/packages/apps/Bluetooth/res/values/config.xml

**Comment by kolanski** [comment]
so, the last question. what target for device select? hammerhead userdebug?

**Comment by lbdroid** [comment]
I really don't know. That question is way outside of the scope of this project.
